/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoppListeRouteImport } from './routes/stopp-liste'
import { Route as OmRouteImport } from './routes/om'
import { Route as KartRouteImport } from './routes/kart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoppStopIdRouteImport } from './routes/stopp.$stopId'

const StoppListeRoute = StoppListeRouteImport.update({
  id: '/stopp-liste',
  path: '/stopp-liste',
  getParentRoute: () => rootRouteImport,
} as any)
const OmRoute = OmRouteImport.update({
  id: '/om',
  path: '/om',
  getParentRoute: () => rootRouteImport,
} as any)
const KartRoute = KartRouteImport.update({
  id: '/kart',
  path: '/kart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoppStopIdRoute = StoppStopIdRouteImport.update({
  id: '/stopp/$stopId',
  path: '/stopp/$stopId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kart': typeof KartRoute
  '/om': typeof OmRoute
  '/stopp-liste': typeof StoppListeRoute
  '/stopp/$stopId': typeof StoppStopIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kart': typeof KartRoute
  '/om': typeof OmRoute
  '/stopp-liste': typeof StoppListeRoute
  '/stopp/$stopId': typeof StoppStopIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kart': typeof KartRoute
  '/om': typeof OmRoute
  '/stopp-liste': typeof StoppListeRoute
  '/stopp/$stopId': typeof StoppStopIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kart' | '/om' | '/stopp-liste' | '/stopp/$stopId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kart' | '/om' | '/stopp-liste' | '/stopp/$stopId'
  id: '__root__' | '/' | '/kart' | '/om' | '/stopp-liste' | '/stopp/$stopId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KartRoute: typeof KartRoute
  OmRoute: typeof OmRoute
  StoppListeRoute: typeof StoppListeRoute
  StoppStopIdRoute: typeof StoppStopIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stopp-liste': {
      id: '/stopp-liste'
      path: '/stopp-liste'
      fullPath: '/stopp-liste'
      preLoaderRoute: typeof StoppListeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om': {
      id: '/om'
      path: '/om'
      fullPath: '/om'
      preLoaderRoute: typeof OmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kart': {
      id: '/kart'
      path: '/kart'
      fullPath: '/kart'
      preLoaderRoute: typeof KartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stopp/$stopId': {
      id: '/stopp/$stopId'
      path: '/stopp/$stopId'
      fullPath: '/stopp/$stopId'
      preLoaderRoute: typeof StoppStopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KartRoute: KartRoute,
  OmRoute: OmRoute,
  StoppListeRoute: StoppListeRoute,
  StoppStopIdRoute: StoppStopIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
